config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root to: "books#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create

    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :genre, :resume, :cover)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">

    <div class="field">
      <h3>Titre</h3>
      <%= form.text_field :title, placeholder: "Entre le titre du livre" %>
    </div>

    <div class="field">
      <h3>Auteur.ice</h3>
      <%= form.text_field :author, placeholder: "Entre l'auteur du livre" %>
    </div>

    <div class="field">
      <h3>Genre(s)</h3>
      <%= form.text_field :genre, placeholder: 'Entre le(s) genre(s) littéraire(s) du livre' %>
    </div>

    <div class="field">
      <h3>Résumé</h3>
      <%= form.text_area :resume, class: 'form-control', placeholder: 'Entre le résumé du livre' %>
    </div>

    <div class="field">
      <h3>Couverture</h3>
      <%= form.text_area :cover, class: 'form-control', placeholder: 'Insère une url de la couverture' %>
    </div>

  </div>

  <%= form.button :submit, class: 'btn btn-outline-light' %>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= link_to "Retour", books_path, class: 'btn btn-outline-light'%>

<% end %>

app/views/books/edit.html.erb
<div class=image>
<%= image_tag 'couronne.png' %>
</div>

<div class=firstdiv>
  <h1>Modifier</h1>
  <h2>ce livre</h2>
</div>

<%= render 'form', book: @book %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class=image>
<%= image_tag 'couronne.png' %>
</div>

<div class=firstdiv>
  <h1>L'Apollothèque</h1>
  <h2>Ta nouvelle bibliothèque en ligne</h2>
</div>

<h3>Nos livres</h3>

  <div class="tableau_index">
    <% @books.each do |book| %>
      <div class="iteration_index">
          <%= link_to book do%>
            <img src="<%=book.cover%>" class="image_index">
            <p><%= book.title %></p>
          <% end %>
      </div>
    <% end %>
  </div>

<br>

app/views/books/new.html.erb
<div class=image>
<%= image_tag 'couronne.png' %>
</div>

<div class=firstdiv>
  <h1>Ajouter</h1>
  <h2>un livre</h2>
</div>

<%= render 'form', book: @book %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class=image>
<%= image_tag 'couronne.png' %>
</div>

<div class="firstdiv">

  <h1>
    <strong>Titre:</strong>
    <%= @book.title %>
  </h1>

  <h2>
    <strong>Auteur:</strong>
    <%= @book.author %>
  </h2>
</div>

<div class="contentShow">

  <div class="part1show">
    <h3>
      <strong>Genre(s):</strong>
    </h3>
    <p>
      <%= @book.genre %>
    </p>


    <h3>
      <strong>Résumé:</strong>
    </h3>
    <p>
      <%= simple_format @book.resume %>
    </p>

  </div>

  <div class="part2show">
    <img src="<%=@book.cover%>" class="image_index">
  </div>
</div>


<div class="buttonShow">
  <%= link_to 'Modifier', edit_book_path(@book), class: 'btn btn-outline-light' %>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= link_to "Retour", books_path, class: 'btn btn-outline-light'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apollotheque</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap" rel="stylesheet">
    <link href="http://fonts.cdnfonts.com/css/gotham" rel="stylesheet">

  </head>

  <body>
    <header class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/books">
          <%= image_tag 'logotheque.png' %>
        </a>

        <span style="color: #fcf6f8 !important">
          <%= link_to "Ajouter un livre", new_book_path %>
        </span>

        <% if user_signed_in? %>
            <%= link_to current_user.email, edit_user_registration_path %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to "Connexion", new_user_session_path %>
            <%= link_to "Inscription", new_user_registration_path %>
        <% end %>
      </div>
    </header>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>

</html>